BUGFIX: owner was not being written out correctly for `popm'.
This commit contains a few changes:

    - a fix to the bug mentioned above
    - maintenance: renamed autogen.sh, got rid of libtool.m4
    - fixed a compilation bug on MacOS

diff --git a/test/test-popm b/test/test-popm
--- a/test/test-popm
+++ b/test/test-popm
@@ -238,6 +238,40 @@ function test_id3v1_only
     rating=$(${popm_scribbu_dir}/scribbu dump v1-only.mp3|grep -F rating|awk '{print $2}')
     [ "$rating" = "196" ] || fail "test_id3v1_only: rating is $rating; should be 196"
 
+    clean_testdir $here $popm_testdir test_id3v1_only
+}
+
+# Test another bug I found with `mppopmd'
+function test_rate_then_count
+{
+    local out
+    local err
+    local stat
+
+    case `uname` in
+        Linux)
+            sed_regex="-r";;
+        Darwin)
+            sed_regex="-E";;
+        *)
+            echo "Unknown system" 2>&1;
+            exit 1;;
+    esac
+
+    here=`pwd`
+    set_testdir ${srcdir} $popm_testdir test_rate_then_count life.mp3
+
+    run_popm out err stat -a -A -b -o sp1ff@pobox.com -r 196 life.mp3
+    test $stat -eq 0 || fail "test_rate_then_count: failed to set rating"
+    rating=$(${popm_scribbu_dir}/scribbu dump life.mp3|grep -F rating|awk '{print $2}')
+    [ "$rating" = "196" ] || fail "test_rate_then_count: rating is $rating; should be 196"
+
+    # Now set the playcount to 1
+    run_popm out err stat -a -A -b -o sp1ff@pobox.com -C 1 life.mp3
+    rating=$(${popm_scribbu_dir}/scribbu dump life.mp3|grep -F rating|awk '{print $2}')
+    [ "$rating" = "196" ] || fail "test_rate_then_count: rating is $rating; should be 196 (2)"
+
+    clean_testdir $here $popm_testdir test_rate_then_count
 }
 
 ###########################################################################
@@ -315,3 +349,4 @@ smoke_tests
 test_issue_1
 test_extant_frames
 test_id3v1_only
+test_rate_then_count
diff --git a/test/test-xtag b/test/test-xtag
--- a/test/test-xtag
+++ b/test/test-xtag
@@ -92,6 +92,25 @@ function smoke_tests()
     clean_testdir $here $popm_testdir xtag_smoke_tests
 }
 
+# Test my fix to a problem I found while running scribbu under `mpd' where the
+# owner wasn't being written out
+function test_owner_bug()
+{
+    local out
+    local err
+    local stat
+
+    here=`pwd`
+    set_testdir ${srcdir} $xtag_testdir xtag_smoke_tests id3v2.3.tag
+
+    run_xtag out err stat -A -a -T 'decade=90s&subgenres=Rock&move-to-cali' -o sp1ff@pobox.com id3v2.3.tag
+    test $stat -eq 0 || fail "smoke_owner_bug: incorrect status"
+    xtag=$(${xtag_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F XTAG|awk '{print $2}')
+    test "$xtag" = "sp1ff@pobox.com" || fail "smoke_test_owner_bug: failed to write owner!"
+
+    clean_testdir $here $popm_testdir xtag_smoke_tests
+}
+
 ###########################################################################
 
 if [ -z "$srcdir" ]; then
@@ -166,3 +185,4 @@ xtag_scribbu_dir=`cd "$xtag_scribbu_dir"; pwd`
 [ -d "$xtag_testdir" ] || mkdir -p "$xtag_testdir"
 xtag_testdir=`cd "$xtag_testdir"; pwd`
 smoke_tests
+test_owner_bug
