Final commit of the `genre' sub-command.
This commit completes the implementation of the `genre' sub-
command:

    1. add'nl tests & fixes for the bugs found therefrom

    2. moved the `xtag' sub-command over to the tagset_processor
       framework

    3. moved the `popm' sub-command over to the tagset_processor
       framework

diff --git a/test/test-genre b/test/test-genre
--- a/test/test-genre
+++ b/test/test-genre
@@ -76,6 +76,7 @@ function smoke_tests()
     v1=$(${genre_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F ID3v1:)
     stat=$?
     [ $stat -eq 0 ] || fail "smoke_tests: failed to add ID3v1 tag"
+    test -f id3v2.3.tag.1 && fail "Ooops-- backup copy was made (1)"
 
     run_genre out err stat -c -C -w 40 id3v2.3.tag
     [ $stat -eq 0 ] || fail "smoke_tests: non-zero status for -w"
@@ -86,20 +87,133 @@ function smoke_tests()
     v1=$(${genre_scribbu_dir}/scribbu dump id3v2.3.tag|grep -E '^AlternRock')
     stat=$?
     [ $stat -eq 0 ] || fail "smoke_tests: bad ID3v1 genre"
+    test -f id3v2.3.tag.1 && fail "Ooops-- backup copy was made (2)"
+
+    run_genre out err stat -c -C -b -G Alt-Rock id3v2.3.tag
+    test $stat -eq 0 || fail "smoke_tests: non-zero status for -G"
+    test -z "$err" || fail "smoke_tests: non-nil stderr for -G"
+    test -z "$out" || fail "smoke_tests: non-nil stdout for -G"
+    tcon=$(${genre_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F TCON)
+    [ "$tcon" = "TCON: Alt-Rock" ] || fail "smoke_tests: wrong TCON: $tcon"
+    v1=$(${genre_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F ID3v1:)
+    stat=$?
+    test $stat -eq 0 || fail "smoke_tests: failed to add ID3v1 tag"
+    # "Art Rock" is the closest match to "Alt-Rock"-- the ID3v1 genre
+    # should have been set to this (unfortunately)
+    art_rock=$(${genre_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F 'Art Rock')
+    stat=$?
+    test $stat -eq 0 || fail "smoke_tests: wrong ID3v1 genre(?)"
+    test -f id3v2.3.tag.1 || fail "Ooops-- backup copy was not made"
+
+    #######################################################################
+    # test tag scoping
+    #######################################################################
+
+    # -2 should leave the ID3v1 genre
+    run_genre out err stat -2 -w 0 id3v2.3.tag
+    test $stat -eq 0 || fail "smoke_tests: non-zero status for -2"
+    art_rock=$(${genre_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F 'Art Rock')
+    stat=$?
+    test $stat -eq 0 || fail "smoke_tests: non-zero -2 changed ID31"
+
+    # TCON is now Blues
+    # genre is Art Rock
+
+    # -1 should leave out the TCON
+    run_genre out err stat -1 -w 2 id3v2.3.tag
+    test $stat -eq 0 || fail "smoke_tests: non-zero status for -1"
+    tcon=$(${genre_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F TCON)
+    test "$tcon" = "TCON: Blues" || fail "smoke_tests: changed ID3v2"
+    country=$(${genre_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F 'Country')
+    stat=$?
+    test $stat -eq 0 || fail "smoke_tests: wrong ID3v1 genre"
+
+    # TCON is Blues
+    # genre is now Country
+
+    # scope by ID3v2 tag
+    run_genre out err stat -t 0 -w 6 id3v2.3.tag
+    test $stat -eq 0 || fail "smoke_tests: non-zero status for -t"
+    tcon=$(${genre_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F TCON)
+    test "$tcon" = "TCON: Grunge" || fail "smoke_tests: wrong TCON: $tcon"
+    grunge=$(${genre_scribbu_dir}/scribbu dump id3v2.3.tag|grep -E '^Grunge')
+    stat=$?
+    test $stat -eq 0 || fail "smoke_tests: wrong ID3v1 genre"
+
+    # finally, check on -W
+    run_genre out err stat genre -W
+    test $stat -eq 0 || fail "smoke_tests: non-zero status for -W"
 
     clean_testdir $here $genre_testdir smoke_tests
 }
 
+function negative_tests
+{
+    local out
+    local err
+    local stat
+
+    here=`pwd`
+    set_testdir ${srcdir} $genre_testdir negative_tests id3v2.3.tag
+
+    # exactly one of -w, -g & -G must be given;
+    # give none
+    run_genre out err stat -c -b id3v2.3.tag
+    test $stat -ne 0 || fail "negative_tests: none of -w, -g & -G given should fail"
+    test -n "$err" || fail "negative_tests: none of -w, -g & -G given should produce an eror message"
+    test -z "$out" || fail "negative_tests: none of -w, -g & -G given should produce no output"
+
+    # give two
+    run_genre out err stat -c -b -w 0 -g Alternative id3v2.3.tag
+    test $stat -ne 0 || fail "negative_tests: two of -w, -g & -G given should fail (1)"
+    test -n "$err" || fail "negative_tests: two of -w, -g & -G given should produce an eror message (1)"
+    test -z "$out" || fail "negative_tests: two of -w, -g & -G given should produce no output (1)"
+
+    # give two
+    run_genre out err stat -c -b -w 0 -G Alternative id3v2.3.tag
+    test $stat -ne 0 || fail "negative_tests: two of -w, -g & -G given should fail (2)"
+    test -n "$err" || fail "negative_tests: two of -w, -g & -G given should produce an eror message (2)"
+    test -z "$out" || fail "negative_tests: two of -w, -g & -G given should produce no output (2)"
+
+    # give two
+    run_genre out err stat -c -b -g Alt-Rock -G Alternative id3v2.3.tag
+    test $stat -ne 0 || fail "negative_tests: two of -w, -g & -G given should fail (3)"
+    test -n "$err" || fail "negative_tests: two of -w, -g & -G given should produce an eror message (3)"
+    test -z "$out" || fail "negative_tests: two of -w, -g & -G given should produce no output (3)"
+
+    # give three
+    run_genre out err stat -c -b -w 0 -g Alt-Rock -G Alternative id3v2.3.tag
+    test $stat -ne 0 || fail "negative_tests: three of -w, -g & -G given should fail"
+    test -n "$err" || fail "negative_tests: three of -w, -g & -G given should produce an eror message"
+    test -z "$out" || fail "negative_tests: three of -w, -g & -G given should produce no output"
+
+    # -t & -1
+    run_genre out err stat -w 8 -1 -t 2 id3v2.3.tag
+    test $stat -ne 0 || fail "negative_tests: -1 & -t should fail"
+    test -n "$err" || fail "negative_tests: -1 & -t should produce an eror message"
+    test -z "$out" || fail "negative_tests: -1 & -t should produce no output"
+
+    # -c & -a
+    run_genre out err stat -w 8 -a -c id3v2.3.tag
+    test $stat -ne 0 || fail "negative_tests: -a & -A should fail"
+    test -n "$err" || fail "negative_tests: -a & -A should produce an eror message"
+    test -z "$out" || fail "negative_tests: -a & -A should produce no output"
+
+    clean_testdir $here $genre_testdir negative_tests
+}
+
+###########################################################################
+#                          parse options & run tests                      #
 ###########################################################################
 
 genre_builddir=../src
 genre_cols=$(tput cols)
-genre_debug=false
-genre_help=false
+genre_debug=no
+genre_help=no
 genre_nargs=0
 genre_scribbu_dir=../src
 genre_testdir=./test-genre-tmp
-genre_verbose=false
+genre_verbose=no
 genre_prev_option=
 for genre_option
 do
@@ -121,11 +235,11 @@ do
     # Options are handled here:
     case $genre_option in
         -d | --de | --deb | --debu | --debug)
-            genre_debug=true;;
+            genre_debug=yes;;
         -h | --he | --hel | --help)
-            genre_help=true;;
+            genre_help=yes;;
         -v | --ve | --ver | --verb | --verbo | --verbose)
-            genre_verbose=true;;
+            genre_verbose=yes;;
         *)
             cat >&2 <<EOF
 Unrecognized option \`$genre_option'.
@@ -136,21 +250,21 @@ EOF
 
 done
 
-if test "$genre_help" == "true"; then
+if test "$genre_help" == "yes"; then
     cat <<EOF
 \`$0' -- test the \`genre' sub-command
 
-TODO(sp1ff): write me!
+Tests for \`scribbu genre'; part of the scribbu test suite.
 EOF
 fi
 
-if test "$genre_verbose" == "true"; then
+if test "$genre_verbose" == "yes"; then
     exec 3>&1
 else
     exec 3> /dev/null
 fi
 
-if test "$genre_debug" == "true"; then
+if test "$genre_debug" == "yes"; then
     set -x
 fi
 
@@ -159,4 +273,4 @@ genre_scribbu_dir=`cd "$genre_scribbu_dir"; pwd`
 [ -d "$genre_testdir" ] || mkdir -p "$genre_testdir"
 genre_testdir=`cd "$genre_testdir"; pwd`
 smoke_tests
-# test_issue_1
+negative_tests
diff --git a/test/test-popm b/test/test-popm
--- a/test/test-popm
+++ b/test/test-popm
@@ -1,9 +1,12 @@
 #!/usr/bin/env bash
 export GUILE_AUTO_COMPILE=0
 
+if [ -z "$srcdir" ]; then
+    echo >&2 "the \`srcdir' environment variable needs to be set to this script's location"
+    exit 1
+fi
 
 source ${srcdir}/test-util
-
 
 # run `scribbu popm ...'
 # usage: run_popm var_to_rcv_stdout var_to_rcv_stderr var_to_rcv_status args...
@@ -43,9 +46,10 @@ function run_popm()
 }
 
 ###########################################################################
-# tests
+#                                   tests                                 #
 ###########################################################################
 
+# "smoke tests"-- if these don't pass, something's very wrong
 function smoke_tests()
 {
     local out
@@ -70,14 +74,14 @@ function smoke_tests()
     stat=$?
     [ $stat -ne 0 ] || fail "smoke_tests: should not have PCNT frame"
 
-    run_popm out err stat --dry-run --create id3v2.3.tag
+    run_popm out err stat --dry-run --create-frame id3v2.3.tag
     [ $stat -eq 0 ] || fail "smoke_tests: non-zero status on dry-run"
-    echo $out|grep -F "creating a new PCNT frame with a count of 0">/dev/null
+    echo $out|grep -F "Creating a new PCNT frame with a play count of 0.">/dev/null
     stat=$?
     [ $stat -eq 0 ] || fail "smoke_tests: failed to find PCNT (dry-run)"
 
     # run it again-- should be there now
-    run_popm out err stat --create id3v2.3.tag
+    run_popm out err stat --create-frame id3v2.3.tag
     [ $stat -eq 0 ] || fail "smoke_tests: non-zero exit status on create"
     ${popm_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F PCNT
     stat=$?
@@ -87,11 +91,13 @@ function smoke_tests()
     pcnt=$(${popm_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F PCNT|awk '{print $2}')
     [ $pcnt = "1" ] || fail "smoke_tests: PCNT is $pcnt; should be 1"
 
-    run_popm out err stat --popularimeter-only -a -o "sp1ff@pobox.com" -r 192 id3v2.3.tag
+    run_popm out err stat --popularimeter-only -A -o "sp1ff@pobox.com" -r 192 id3v2.3.tag
     popm=$(${popm_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F POPM|awk '{print $2}')
     [ "$popm" = "sp1ff@pobox.com" ] || fail "smoke_tests: no POPM"
     rating=$(${popm_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F rating|awk '{print $2}')
     [ "$rating" = "192" ] || fail "smoke_tests: rating is $rating; should be 192"
+    pcnt=$(${popm_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F counter|awk '{print $2}')
+    [ "$pcnt" = "01" ] || fail "smoke_tests: PCNT is $pcnt; should be 01 (2)"
 
     run_popm out err stat --count=11 id3v2.3.tag
     [ $stat -eq 0 ] || fail "smoke_tests: non-zero status on pc => 11"
@@ -110,10 +116,16 @@ function smoke_tests()
     rating=$(${popm_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F rating|awk '{print $2}')
     [ "$rating" = "1" ] || fail "smoke_tests: rating is $rating; should be 1"
 
-    run_popm out err stat --rating=x -L id3v2.3.tag
-    [ $stat -eq 0 ] || fail "smoke_tests: non-zero status on linear rating"
+    # Let's test recursion
+    mkdir -p sub1/sub2 || fail "smoke_tests: failed to make test sub-directories"
+    cp  id3v2.3.tag sub1/sub2 || fail "smoke_tests: failed to copy test file"
+
+    run_popm out err stat --rating=##### id3v2.3.tag sub1
+    test $stat -eq 0 || fail "smoke_tests: non-zero status on star rating (2)"
     rating=$(${popm_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F rating|awk '{print $2}')
-    [ "$rating" = "26" ] || fail "smoke_tests: rating is $rating; should be 1"
+    test "$rating" = "255" || fail "smoke_tests: rating is $rating; should be 255"
+    rating=$(${popm_scribbu_dir}/scribbu dump sub1/sub2/id3v2.3.tag|grep -F rating|awk '{print $2}')
+    test "$rating" = "255" || fail "smoke_tests: rating is $rating; should be 255 (2)"
 
     clean_testdir $here $popm_testdir smoke_tests
 
@@ -139,20 +151,17 @@ function test_issue_1
     here=`pwd`
     set_testdir ${srcdir} $popm_testdir test_issue_1 id3v2.3.tag
 
-    run_popm out err stat --create --owner=sp1ff@pobox.com --rating=255 id3v2.3.tag
-    stat=$?
+    run_popm out err stat --create-frame --owner=sp1ff@pobox.com --rating=255 id3v2.3.tag
+    # stat=$?
     [ $stat -eq 0 ] || fail "test_issue_1: non-zero exit status on create"
 
     ${popm_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F PCNT
-    stat=$?
     [ $stat -eq 0 ] || fail "test_issue_1: should have PCNT frame"
 
     ${popm_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F POPM
-    stat=$?
     [ $stat -eq 0 ] || fail "test_issue_1: should have POPM frame"
 
     run_popm out err stat id3v2.3.tag
-    stat=$?
     [ $stat -eq 0 ] || fail "test_issue_1: non-zero exit status on update"
 
     pcnt=`${popm_scribbu_dir}/scribbu dump id3v2.3.tag|grep -F PCNT|sed ${sed_regex} 's/PCNT: ([0-9]+)/\1/'`
@@ -165,12 +174,48 @@ function test_issue_1
     clean_testdir $here $popm_testdir test_issue_1
 }
 
-###########################################################################
+# Make sure that when creating a PCNT or a POPM frame, when a such a frame is
+# already present, picks up the play count from the extant frame.
+function test_extant_frames()
+{
+    local out
+    local err
+    local stat
 
-if [ -z "$srcdir" ]; then
-    echo >&2 "the \`srcdir' variable needs to be set to this script's location"
-    exit 1
-fi
+    case `uname` in
+        Linux)
+            sed_regex="-r";;
+        Darwin)
+            sed_regex="-E";;
+        *)
+            echo "Unknown system" 2>&1;
+            exit 1;;
+    esac
+
+    here=`pwd`
+    set_testdir ${srcdir} $popm_testdir test_extant_frames cerulean.mp3
+
+    # This file has a POPM frame with a play count of zero-- bump that.
+    run_popm out err stat cerulean.mp3
+    test $stat -eq 0 || fail "test_extant_frames: failed to increment counter"
+    pcnt=`${popm_scribbu_dir}/scribbu dump cerulean.mp3|grep -F counter|sed ${sed_regex} 's/counter: ([0-9]+)/\1/'`
+    test "$pcnt" == "01" || fail "test_extant_frames: POPM counter should be one, got $pcnt"
+
+    # Now create a PCNT frame, see if it picks up the counter from the existing
+    # POPM
+    run_popm out err stat --create-frame --owner=sp1ff@pobox.com --rating=255 cerulean.mp3
+    test $stat -eq 0 || fail "test_extant_frames: failed to create POPM"
+    pcnt=`${popm_scribbu_dir}/scribbu dump cerulean.mp3|grep -F PCNT|sed ${sed_regex} 's/PCNT: ([0-9]+)/\1/'`
+    test "$pcnt" == "1" || fail "test_extant_frames: PCNT should be one, got $pcnt"
+
+    clean_testdir $here $popm_testdir test_extant_frames
+}
+
+
+###########################################################################
+# parse options; `make check' will pass none, so be sure no options means
+# execute test suite normally
+###########################################################################
 
 popm_builddir=../src
 popm_cols=$(tput cols)
@@ -240,3 +285,4 @@ popm_scribbu_dir=`cd "$popm_scribbu_dir"; pwd`
 popm_testdir=`cd "$popm_testdir"; pwd`
 smoke_tests
 test_issue_1
+test_extant_frames
